### ISSUE TITLE
Confused about attributes

### ISSUE THREAD

**Issue by gaggle** [alexfalkowski/chef-teamcity#17]
Hi @alexfalkowski,

Sorry if this is a naive question, but I can't figure out how to actually use your cookbook. I'm not sure how to properly fill out the required attributes.

At this point I've filled out `['server']['database']['username']` / `['password']` with some strings, but the cookbook now complains about an invalid `['server']['database']['jar']`. But how is that supposed to be filled out? Do you have an example where all the required variables are filled out that I can learn from?

I've committed my progress to this [vagrant-chef-teamcity-example] (https://github.com/gaggle/vagrant-chef-teamcity-example/blob/master/Vagrantfile) repo. Any help appreciated.

**Comment by alexfalkowski** [comment]
Hi @gaggle,

No problem, sometimes I get confused with this stuff too. If you look at my Vagrantfile this should help you get there https://github.com/alexfalkowski/chef-teamcity/blob/master/Vagrantfile

Please advise if you need any further information.

Regards,
Alex

**Comment by gaggle** [comment]
Oh.. huh, sorry, I somehow missed your Vagrantfile. I looked through the cookbook as downloaded by librarian-chef as well as the readme on Github, but somehow forgot to look through your repo's files. Whoops!

With that in hand I easily got a local teamcity up and running, thank you for providing the cookbook.

**Comment by alexfalkowski** [comment]
No problem. Glad I could help :)
